// ProgramacionWeb/WikiGames_Angular/src/app/vistas/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Usuario } from 'src/app/compartidos/clases/usuario';
import { LoginService } from 'src/app/compartidos/servicios/login.service';
import { Router } from '@angular/router';
@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
  })
  export class LoginComponent implements OnInit {
  // Atributos
  public usuario: Usuario;
  constructor(private loginService: LoginService,private router:Router){
  this.usuario = new Usuario();
  }
  ngOnInit(): void {
  }
  public submit(): void {
  this.loginService.login(this.usuario).subscribe(
  (data: number) => {
  localStorage.setItem('nombreUsuario', this.usuario.nombre);
  localStorage.setItem('miTokenPersonal',`${ data }`);
  this.router.navigate(['/']);
  
  
  },
  (error: Error) => {
  console.error("Error al realizar el acceso");
  }
  )
  }
  public reload_page():void{
    window.location.reload();
  }
  }
    <div class="container col-2"> 
      <div class="guybrush"></div>
    </div>
    <div class="container row-justify-content-md-left ">
        <div class="col-3">
          <h2 class="heading"> Formulario de Inicio de Sesión</h2>
          <div class="container">
            <form (ngSubmit)="submit()" #usuarioForm="ngForm">
              <fieldset>
          <div class="form-group">
              <label for="nombre" class="form-label mt-4 ">Usuario</label>
              <input type="text" class="form-control text-muted" [(ngModel)]="usuario.nombre"
              name="nombre" #nombre="ngModel" required aria-describedby="emailHelp" placeholder="Insertar Usuario">
              <small id="emailHelp" class="form-text text-muted">El nombre de usuario será visible en el menú de navegación.</small>
            </div>
            <div class="form-group">
              <label for="contrasegna" class="form-label mt-4">Constraseña</label>
              <input type="password" class="form-control" [(ngModel)]="usuario.contrasegna"
              name="contrasegna" #contrasegna="ngModel" required minlength="4" placeholder="Insertar Contraseña">
            </div>
            <small id="emailHelp" class="form-text text-muted">La contraseña debe tener como mínimo 4 dígitos.</small><br/>
            <button type="submit" (click)="reload_page()" [disabled]="!usuarioForm.form.valid" class="btn btn-primary mb-5">Acceder</button>
          </fieldset>
      </form>
          </div>
        </div>
        
       
        </div>

// ProgramacionWeb/GifWorld_React/reactapi/src/components/Login.js
import React from 'react'
import './Login.css'

export default function Login(){
    return <div class="container" id="contenedor-top">
    <div class="row">
    <div class="col-6">
      <div class="row border-bottom border-primary justify-content-center text-center" >
        <div class="col ">
          <span>
            <h1><b>Formulario de Inicio de Sesión </b></h1>
          </span>
        </div>
      </div>
      <div class="container">
        <form>
          <fieldset>
            <div class="form-group">
              <label for="nombre" class="form-label mt-4 "><h2><b>Usuario</b></h2></label>
              <input type="text" class="form-control " name="nombre" required aria-describedby="emailHelp" placeholder="Insertar Usuario"/>
              <small id="emailHelp" class="form-text "><b>El nombre de usuario será visible en el menú de
                navegación.</b></small>
            </div>
            <div class="form-group">
              <label for="contrasegna" class="form-label mt-4"><h2><b>Contraseña</b></h2></label>
              <input type="password" class="form-control"name="contrasegna"
                 required minlength="4" placeholder="Insertar Contraseña"/>
            </div>
            <small id="emailHelp" class="form-text mb-3"><b>La contraseña debe tener como mínimo 4
              dígitos.</b></small><br />
            <button type="submit"
              class="btn btn-primary mb-5">Acceder</button>
          </fieldset>
        </form>
      </div>
    </div>
    <div class="col-6">
      <img src="/formulario2.png" class="img-fluid" alt="..."/>
    </div>
  </div>
  </div>
}
